import { StyleSheet } from 'react-native';

export const paymentOptionStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#006b8fff',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  loadingContainer: {
    flex: 1,
    backgroundColor: '#F5F7FA',
    justifyContent: 'center',
    alignItems: 'center',
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
    color: '#6c757d',
    fontWeight: '500',
  },
  errorText: {
    fontSize: 18,
    color: '#dc3545',
    textAlign: 'center',
    fontWeight: '600',
  },
  card: {
    backgroundColor: '#ffffff',
    borderRadius: 16,
    padding: 24,
    width: '100%',
    maxWidth: 400,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
    elevation: 8,
  },
  razorpayLogo: {
    width: 140,
    height: 35,
    alignSelf: 'center',
    marginBottom: 24,
  },
  orderIdText: {
    fontSize: 15,
    color: '#6c757d',
    marginBottom: 16,
    textAlign: 'left',
    fontWeight: '500',
  },
  orderLabel: {
    fontSize: 17,
    fontWeight: '700',
    color: '#212529',
    marginBottom: 8,
  },
  customerName: {
    fontSize: 20,
    fontWeight: '600',
    color: '#212529',
    marginBottom: 4,
  },
  customerContact: {
    fontSize: 15,
    color: '#6c757d',
    marginBottom: 4,
  },
  divider: {
    height: 1,
    backgroundColor: '#e9ecef',
    marginVertical: 20,
  },
  productRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  productName: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#212529',
  },
  productPrice: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#212529',
  },
  paymentOptionsContainer: {
    marginBottom: 24,
  },
  paymentOptionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#e9ecef',
  },
  paymentOptionLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  paymentOptionIcon: {
    width: 28,
    height: 28,
    marginRight: 18,
    tintColor: '#343a40',
  },
  paymentOptionLabel: {
    fontSize: 17,
    color: '#212529',
    fontWeight: '500',
  },
  arrowIcon: {
    width: 20,
    height: 20,
    tintColor: '#adb5bd',
  },
  payButton: {
    backgroundColor: '#E7613C',
    borderRadius: 10,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 20,
    shadowColor: '#E7613C',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 5,
    elevation: 6,
  },
  payButtonText: {
    color: '#fff',
    fontSize: 18,
    fontWeight: 'bold',
  },
});